name: Upload Local Build to Itch.io

on:
  push:
    branches:
      - main  # Solo se ejecuta cuando haces push a main (cámbialo si es necesario)

jobs:
  upload:
    name: Upload Local Build to Itch.io
    runs-on: ubuntu-latest  # También puedes usar windows-latest o macos-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Compress Build
        run: |
          zip -r build.zip release/  # Asegúrate de que "build/" tiene el juego exportado localmente
          
      - name: Remove existing Butler
        run: rm -f /usr/local/bin/butler ~/.itch/butler
  
      - name: Install Butler
        run: |
          mkdir -p ~/.itch
          curl -L -o ~/.itch/butler https://broth.itch.ovh/butler/linux-amd64/head/butler
          chmod +x ~/.itch/butler
          sudo mv ~/.itch/butler /usr/local/bin/butler

      - name: Upload to Itch.io
        run: |
          butler push build.zip windestroy/bullet-path:html5
        env:
          BUTLER_API_KEY: ${{ secrets.ITCHIO_API_KEY }}
