name: Upload Local Build to Itch.io

on:
  push:
    branches:
      - main # Solo se ejecuta cuando haces push a main (cámbialo si es necesario)

jobs:
  upload:
    name: Upload Local Build to Itch.io
    runs-on: ubuntu-latest # También puedes usar windows-latest o macos-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Compress Build
        run: |
          zip -r build.zip release/  # Asegúrate de que "build/" tiene el juego exportado localmente

      - name: Remove existing Butler
        run: rm -f /usr/local/bin/butler ~/.itch/butler

      - name: Check Unzip Version
        run: unzip -v

      - name: Install Butler
        run: |
          echo "Descargando Butler..."
          curl -L https://broth.itch.zone/butler/linux-amd64/archive/default.zip -o ~/butler.zip --verbose && echo "Descarga completada." || echo "Error en la descarga."
          echo "Leer Butler..."
          cat ~/butler.zip
          echo "File Butler..."
          file ~/butler.zip
          echo "Extrayendo Butler..."
          unzip ~/butler.zip -d ~/ && echo "Extracción completada." || echo "Error al extraer."
          echo "Dando permisos de ejecución..." 
          chmod +x ~/butler && echo "Permisos aplicados." || echo "Error al aplicar permisos."
          echo "Moviendo Butler a /usr/local/bin/..."
          sudo mv ~/butler /usr/local/bin/butler && echo "Movimiento completado." || echo "Error al mover el archivo."

      - name: Check Butler Version
        run: butler -v

      - name: Upload to Itch.io
        run: |
          butler push build.zip windestroy/bullet-path:html5
