name: Upload Local Build to Itch.io

on:
  push:
    branches:
      - main # Solo se ejecuta cuando haces push a main (cámbialo si es necesario)

jobs:
  upload:
    name: Upload Local Build to Itch.io
    runs-on: ubuntu-latest # También puedes usar windows-latest o macos-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Compress Build
        run: |
          zip -r build.zip release/  # Asegúrate de que "build/" tiene el juego exportado localmente

      - name: Remove existing Butler
        run: rm -f /usr/local/bin/butler ~/.itch/butler
        
      - name: Check Unzip Version
        run: unzip -v

      - name: Install Butler
        run: |
          curl -L -o ~/butler.zip https://broth.itch.ovh/butler/linux-amd64/archive/default.zip
          unzip ~/butler.zip -d ~/
          chmod +x ~/butler
          sudo mv ~/butler /usr/local/bin/butler

      - name: Check Butler Version
        run: butler -v

      - name: Upload to Itch.io
        run: |
          butler push build.zip windestroy/bullet-path:html5
